"""Self-hosted building tile endpoints.

    GET /tiles/buildings/{z}/{x}/{y}.json  → GeoJSON building tile w/ height metadata
    GET /tiles/buildings/metadata          → tile DB metadata

Serves GeoJSON tiles from a local SQLite DB generated by
`tiles/generate_building_tiles.py`. This is a *self-hosted* dataset — distinct
from `routes/tiles.py`, which proxies *external* QLD ArcGIS cadastral data with
a disk cache. Different mechanism, kept in its own module.

The SQLite connection is opened lazily on first request and kept alive for the
process. `ROOT_DIR` is lazy-imported from `server` inside the path resolver so
this module loads cleanly regardless of import order.
"""
from __future__ import annotations

import gzip
import logging
import os
import sqlite3
from pathlib import Path

from fastapi import APIRouter, Response

logger = logging.getLogger("server")
router = APIRouter()

_EMPTY_FC = b'{"type":"FeatureCollection","features":[]}'
_TILE_HEADERS = {"Access-Control-Allow-Origin": "*", "Cache-Control": "public, max-age=86400"}

_building_tile_db: sqlite3.Connection | None = None
_tile_db_path: str | None = None


def _resolve_tile_db_path() -> str:
    """Resolve the building tile DB across both dev and container layouts.

    Dev:        /app/backend/server.py  -> /app/tiles/buildings.db  (ROOT_DIR.parent / 'tiles')
    Container:  /app/server.py          -> /tiles/buildings.db
    Pick the first candidate that exists; fall back to the canonical dev path
    so the warning log still points at the expected location.
    """
    from server import ROOT_DIR  # noqa: WPS433 — lazy to avoid import-order coupling
    candidates = [
        ROOT_DIR.parent / 'tiles' / 'buildings.db',
        ROOT_DIR / 'tiles' / 'buildings.db',
        Path('/tiles/buildings.db'),
        Path('/app/tiles/buildings.db'),
    ]
    for p in candidates:
        if os.path.exists(str(p)):
            return str(p)
    return str(candidates[0])


def _get_tile_db() -> sqlite3.Connection | None:
    global _building_tile_db, _tile_db_path
    if _building_tile_db is None:
        if _tile_db_path is None:
            _tile_db_path = _resolve_tile_db_path()
        if os.path.exists(_tile_db_path):
            _building_tile_db = sqlite3.connect(_tile_db_path, check_same_thread=False)
            logger.info(f"Building tile DB loaded: {_tile_db_path}")
        else:
            logger.warning(f"Building tile DB not found: {_tile_db_path}")
    return _building_tile_db


@router.get("/tiles/buildings/{z}/{x}/{y}.json")
async def get_building_tile(z: int, x: int, y: int):
    """Serve self-hosted building GeoJSON tiles with rich height metadata."""
    conn = _get_tile_db()
    if conn is None:
        return Response(content=_EMPTY_FC, media_type="application/json", headers=_TILE_HEADERS)
    row = conn.execute('SELECT data FROM tiles WHERE z=? AND x=? AND y=?', (z, x, y)).fetchone()
    if row is None:
        return Response(content=_EMPTY_FC, media_type="application/json", headers=_TILE_HEADERS)
    data = gzip.decompress(row[0])
    return Response(content=data, media_type="application/json", headers=_TILE_HEADERS)


@router.get("/tiles/buildings/metadata")
async def get_building_tile_metadata():
    """Return metadata about the self-hosted building tiles."""
    conn = _get_tile_db()
    if conn is None:
        return {"error": "Building tile DB not available"}
    rows = conn.execute('SELECT name, value FROM metadata').fetchall()
    return {r[0]: r[1] for r in rows}
